### ISSUE TITLE
Pure rust unwinder

### ISSUE THREAD

**Issue by roblabla** [MegatonHammer/megaton-hammer#13]
We'll want to port libpanic_unwind at one point, but it relies on libgcc (among other backends). This is not rust :scream:.

We are going to need to write our own unwinder. Fun times ahead.

**Comment by FenrirWolf** [comment]
A few people in [this thread](https://internals.rust-lang.org/t/is-there-any-pure-rust-solution-for-libgcc-s-so-in-libunwind/5998/14) have some tentative ideas about how to make a pure rust unwinder. Might be worth collaborating with them.

**Comment by roblabla** [comment]
Getting kinda sick of having to reboot my console each time I panic. So I started looking into getting an unwinder up. https://refspecs.linuxfoundation.org/LSB_3.0.0/LSB-PDA/LSB-PDA/ehframechpt.html is a good place to start.

**Comment by roblabla** [comment]
We've got a pure rust unwinder more or less integrated. We have no backtraces yet.
