### ISSUE TITLE
Get rid of core_io

### ISSUE THREAD

**Issue by roblabla** [MegatonHammer/megaton-hammer#15]
It turns out core_io ties us to a specific nightly version, and needs to be continuously updated to use latest nightlies. This... absolutely sucks. Either we should figure a plan to get core_io to attempt compiling on the latest nightly using whatever latest patch it has, or we should find an alternative.

**Comment by FenrirWolf** [comment]
The natural solution is to port enough of `std` to use `std::io` instead, but of course that just shifts the problem from "keeping core_io in sync with nightly" to "keeping libstd in sync with nightly"

**Comment by roblabla** [comment]
The `megaton-hammer` crate will be nostd since it will be used *by* std. So we'll probably still need some similar facilities to `core_io`.

**Comment by FenrirWolf** [comment]
Ah right, that makes sense
