### ISSUE TITLE
Pre-main crash outside AceLoader

### ISSUE THREAD

**Issue by roblabla** [MegatonHammer/megaton-hammer#28]
When ran outside AceLoader (for instance, as a KIP1, using nspwn, under hbl), we get a premain crash.

**Comment by kitlith** [comment]
May have something to do with:
https://github.com/MegatonHammer/megaton-hammer/blob/12d4ae676fce7975958beb8d32f29501c8f970a4/megaton-hammer/src/loader/mod.rs#L252-L254

I would think that as kip1 or via nspwn you wouldn't have a loader context, so this would definately fail.

**Comment by roblabla** [comment]
Then entry would be NULL, and so we wouldn't even enter the for loop (https://github.com/MegatonHammer/megaton-hammer/blob/12d4ae676fce7975958beb8d32f29501c8f970a4/megaton-hammer/src/loader/mod.rs#L199)

**Comment by kitlith** [comment]
Ah, that makes sense. I missed something else as well when reading through the code.

**Comment by roblabla** [comment]
At least when running under twili, we're back to working now. I need to check that it works under HBL.
